version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: real_estate_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yeayyeab2
      MYSQL_DATABASE: real_estatedb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --pid-file=/var/lib/mysql/mysqld.pid
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "--password=yeayyeab2",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build:
      context: ./Backend
    container_name: real_estate_backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_DATABASE: real_estatedb
      DB_USERNAME: root
      DB_PASSWORD: yeayyeab2
    ports:
      - "5000:80"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-2
    container_name: real_estate_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
